trigger:
  branches:
    include:
      - main
      - develop
      - feature/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore ./src/AutoDevOpsAI.sln
  displayName: 'Restore packages'

- script: |
    dotnet build ./src/AutoDevOpsAI.sln --configuration $(buildConfiguration) --no-restore
  displayName: 'Build solution'

- script: |
    dotnet test ./src/AutoDevOpsAI.sln --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run tests'
